name: demo-iio-tools
version: '0.2'
summary: a demo for iio tools
description: |
  This is iio tools for testing iio interface in gadget snap

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  iio:
    plugin: make
    source: iio/
    artifacts:
        - iio_event_monitor
        - iio_generic_buffer
        - lsiio
  st-sensor:
    plugin: dump
    source: st_sensor/
    organize:
        sensor_test: bin/

apps:
    iio-event-monitor:
      command: iio_event_monitor
      plugs:
          - iio
          - hardware-observe
    lsiio:
      command: lsiio
      plugs:
          - iio
          - hardware-observe
    iio-generic-buffer:
      command: iio_generic_buffer
      plugs:
          - iio
          - hardware-observe
    st-sensor:
      command: st_sensor
      plugs:
          - iio
          - hardware-observe
