name: demo-iio-tools
version: '0.1'
summary: a demo for iio tools
description: |
  This is iio tools for testing iio interface in gadget snap

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  iio:
    plugin: make
    source: iio/
    artifacts:
        - iio_event_monitor
        - iio_generic_buffer
        - lsiio
        - iio_test
        - iio_sysfs_test.sh

apps:
    iio-event-monitor:
      command: iio_event_monitor
      plugs:
          - iio
          - hardware-observe
          - i2c
    lsiio:
      command: lsiio
      plugs:
          - iio
          - hardware-observe
          - i2c
    iio-generic-buffer:
      command: iio_generic_buffer
      plugs:
          - iio
          - hardware-observe
          - i2c
    iio-test:
      command: iio_test
      plugs:
          - iio
          - hardware-observe
          - i2c
    iio-sysfs-test:
      command: iio_sysfs_test.sh
      plugs:
          - iio
          - hardware-observe
          - i2c
